name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Git Describe
        id: ghd
        uses: proudust/gh-describe@v1
        with:
          default: 0.0.0

      - name: Install Dependencies
        run: npm ci

      - name: Lint and Test
        run: npm test

      - name: Build
        run: npm run build
        env:
          GIT_DESCRIBE: ${{ steps.ghd.outputs.describe }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ddlc-jp-sheet-script@${{ steps.ghd.outputs.describe }}
          path: dist

      - if: github.ref == 'refs/heads/master'
        name: Deploy
        run: echo "$CLASPRC" > ~/.clasprc.json && npm run deploy
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
