name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Restore Dependencies
        run: echo 'export const version = "";' >version.ts && deno cache *.ts **/*.ts npm:@google/clasp@2.4.2 --reload

      - name: Lint and Test
        run: deno task test

      - name: Build
        run: deno task build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ddlc-jp-sheet-script@${{ steps.ghd.outputs.describe }}
          path: dist

      - if: github.ref == 'refs/heads/master'
        name: Deploy
        run: echo "$CLASPRC" > ~/.clasprc.json && deno task deploy
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
