name: ncu

on:
  repository_dispatch:
    types: [ncu]
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  ncu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Use npm cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Run npm-check-updates
        run: |
          sudo npm install -g npm-check-updates
          npx ncu -u
          npm install
          npm audit fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-deps
          commit-message: ':arrow_up: 依存関係のアップデート'
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: 依存関係のアップデート
          body: |
            この Pull Request は GitHub Actions により自動生成されています。
            毎朝 6 時に [raineorshine/npm-check-updates](https://github.com/raineorshine/npm-check-updates) を使用して更新されます。
          labels: automated pr
          assignees: proudust
          reviewers: proudust
